[listen]
api = "0.0.0.0:3302"
publish = "0.0.0.0:3303"

[api]
#disable or not api service
disable = false
#access api token
token = "guest"

[publish]
#these http headers will be ignored when access to consumer's url
#Headers : "User-Agent Token RouteKey Host Expect Accept-Encoding  Content-Length Connection"  will be ignored by force
IgnoreHeaders = []
#the publisher's real ip will be set in this http header when access to consumer's url
RealIpHeader = "X-Forwarded-For"

[consume]
#access consumer url  fail and then how many seconds to sleep and retry
FailWait = 50
#consumer's goroutine occur error and then how many seconds to sleep and retry
GoFailWait = 3
DataFile = "message.json"

[rabbitmq]
host = "127.0.0.1"
port = 5672
username = "guest"
password = "guest"
vhost = "/"
#the queue and exchange default prefix
prefix = "wmq."

[log]
filename="log/comb.log"
maxSize=1048576
maxLine=1000000
dateSlice="d"
jsonFormat=true


