[listen]
api = "0.0.0.0:3302"
publish = "0.0.0.0:3303"

[api]
disable = false
tokenHeaderName = "WMQX_API_TOKEN"
token = "guest"

[publish]
messageTokenHeader = "WMQX_MESSAGE_TOKEN"
messageRouteKeyHeader = "WMQX_MESSAGE_ROUTEKEY"
# these http headers will be ignored when access to consumer's url
# Headers : "User-Agent Token RouteKey Host Expect Accept-Encoding  Content-Length Connection"  will be ignored by force
ignoreHeaders = [
    "WMQX_MESSAGE_TOKEN",
    "WMQX_MESSAGE_ROUTEKEY",
]
# the publisher's real ip will be set in this http header when access to consumer's url
RealIpHeader = "X-Forwarded-For"

[consume]
# consumer url consume fail retry sleep timeout (s)
failRetryTime = 5

[rabbitmq]
host = "127.0.0.1"
port = 5672
username = "test"
password = "123456"
vhost = "/"
poolNumber = 20
heartbeat = 2
connTimeout = 4
prefix = "wmqx."

[message]
record_type="file"
filename="./message.json"
jsonBeautify=true

[log.console]
level="debug"
color=true
jsonFormat=false
showFileLine=false

[log.file]
level="debug"
filename="log/wmqx.log"
maxSize=1048576
maxLine=1000000
dateSlice="d"
jsonFormat=true

[log.file.levelFilename]
error="log/error.log"
info="log/info.log"

